/**
 * ReportTab.jsx — Tab 4: PDF / Markdown report download + preview.
 */
import { useState } from "react";

export default function ReportTab({ results, selectedIdx, downloadPdf, downloadMarkdown }) {
  const sol = results.pareto_solutions[selectedIdx] || results.pareto_solutions[0];

  // Build a simple markdown preview from the solution data
  const assignments = sol?.assignments || [];

  const mdPreview = `
# Green Fleet Deployment Strategy Report — Solution #${selectedIdx + 1}
**Project**: SIH26138 Egreen Quanta | **Optimizer**: MOQPSO

## 1. Executive Summary & KPIs
- **Total Voyage Fuel Cost**: $${sol?.raw_j1_cost?.toLocaleString(undefined, { maximumFractionDigits: 2 }) ?? "-"}
- **Total Lifecycle GHG Emissions**: ${(sol?.raw_j2_emissions / 1000)?.toFixed(2)} metric tons CO2eq
- **Schedule Reliability**: ${sol?.raw_j3_reliability?.toFixed(0)} / ${assignments.length} legs on-time
- **Total Unmet Cargo Demand**: ${sol?.unmet_demand?.toLocaleString(undefined, { maximumFractionDigits: 0 })} tons
- **Regulatory CII Violations**: ${sol?.cii_violations} vessels
- **Port Fuel Availability Violations**: ${sol?.fuel_violations}

## 2. Optimal Vessel-to-Route Assignments
| Vessel | Route | Speed (kts) | Fuel | Cargo (t) | Load % | Transit (h) | On-Time | Cost ($) | GHG (t CO2eq) |
|--------|-------|-------------|------|-----------|--------|-------------|---------|----------|----------------|
${assignments.map(a =>
  `| ${a.vessel_id} | ${a.route_id} | ${a.speed_knots.toFixed(1)} | ${a.fuel_type} | ${a.cargo_load_tons.toLocaleString(undefined, { maximumFractionDigits: 0 })} | ${(a.cargo_load_fraction * 100).toFixed(0)}% | ${a.transit_time_hours.toFixed(1)} | ${a.on_time ? "Yes" : "No"} | $${a.fuel_cost.toLocaleString(undefined, { maximumFractionDigits: 0 })} | ${a.ghg_emissions_tons.toFixed(1)} |`
).join("\n")}

## 3. Scenario Configuration
${Object.entries(results.scenario_params || {}).map(([k, v]) => `- **${k}**: ${v}`).join("\n")}

---
*Generated by Maritime Q — MOQPSO Green Fleet Dashboard (FastAPI + React)*
`.trim();

  return (
    <div>
      <div className="card">
        <div className="card-title">Export Deployment Strategy Report for Solution #{selectedIdx + 1}</div>
        <div className="two-col" style={{ marginBottom: 20 }}>
          <div>
            <h4 style={{ color: "var(--text-primary)", marginBottom: 8 }}>📄 Executive PDF Document</h4>
            <p style={{ fontSize: "0.82rem", color: "var(--text-muted)", marginBottom: 14 }}>
              Complete executive PDF containing KPIs, vessel allocation tables, and scenario parameters.
            </p>
            <button className="dl-btn dl-btn-pdf" onClick={() => downloadPdf(selectedIdx)}>
              ⬇️ Download Executive PDF Report
            </button>
          </div>
          <div>
            <h4 style={{ color: "var(--text-primary)", marginBottom: 8 }}>📝 Markdown Strategy Document</h4>
            <p style={{ fontSize: "0.82rem", color: "var(--text-muted)", marginBottom: 14 }}>
              Markdown summary suitable for technical documentation and version-controlled logging.
            </p>
            <button className="dl-btn dl-btn-md" onClick={() => downloadMarkdown(selectedIdx)}>
              ⬇️ Download Markdown Report (.md)
            </button>
          </div>
        </div>

        <hr />
        <div style={{ marginTop: 16 }}>
          <h4 style={{ color: "var(--text-primary)", marginBottom: 12 }}>Report Preview:</h4>
          <div className="md-preview">
            <pre style={{ whiteSpace: "pre-wrap", fontFamily: "Inter, sans-serif", fontSize: "0.8rem", lineHeight: 1.7 }}>
              {mdPreview}
            </pre>
          </div>
        </div>
      </div>
    </div>
  );
}
